### PR TITLE
Fix/bug 46 graph text overlap

### LINKED ISSUE #46: [BUG]: Dependecy graph labels are overlapped
### Describe the bug

In the dependency graph the text and colour labels are overlapped making some part of text invisible

### Steps to reproduce

1. Login to dashboard
2. Click on Dependency graph 
3. See the rendered graph with text overlapped with colour labels

### Expected behavior

All the text in graph nodes clearly visible

### What is actually happening?

The text in graph nodes are not properly visible due to colourded box being overlapped with it

### Screenshots

_No response_

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by sarthakm-dev**
# Pull Request Description

This pull request addresses the following issue:

**Feature**: [GitHub Issue #46 ](https://github.com/mindfiredigital/monodog/issues/46)

### Changes Made:

- Fixed arrow connection points logic to point to border of nodes instead of center in Graphvisualization.tsx
- Updated DependencyDetails array icon css style to render arrow inline with the text
- Updated packages type definition in DependencyGraph.tsx to resolve vs-code errors

## Screenshots (if appropriate):

Before
Screenshot (1)

After
Screenshot (2)

### Checklist:

- [x] Fix graph node styling
- [x] Fix arrow target logic
- [x] Ensure all components are properly typed with TypeScript.
- [x] Add or update unit tests for new functionality.
- [x] Update documentation (comments, README, etc.) to reflect changes.
- [x] The file(s) or folder(s) now contain changes as specified in the issue I worked on.
- [x] Check build, test, lint and format by run running command `pnpm run build` at root directory.
- [x] I certify that I ran the checklist.

### Testing:

- All test cases for dashboard component passes

## Closing

Closes #46

### CODE REVIEW

File: apps/dashboard/src/components/modules/dependency-graph/components/GraphVisualization.tsx [hunk 1]
```diff
@@ -14,6 +14,25 @@ export default function GraphVisualization({
   onPackageHover,
   layout,
 }: GraphVisualizationProps) {
+  const getConnectionPoints = (pkg: any, dep: any) => {
```
Comment (anandmindfire) [inline apps/dashboard/src/components/modules/dependency-graph/components/GraphVisualization.tsx]: create utils for it

File: apps/dashboard/src/components/modules/dependency-graph/components/GraphVisualization.tsx [hunk 2]
```diff
@@ -26,52 +45,30 @@ export default function GraphVisualization({
...
+                    refY="5"
+                    markerWidth="6"
+                    markerHeight="6"
+                    orient="auto-start-reverse"
                   >
                     <path
-                      d="M0,0 L0,6 L9,3 z"
-                      fill={isHighlighted ? '#3B82F6' : '#6B7280'}
+                      d="M 0 0 L 10 5 L 0 10 z"
+                      fill={isHighlighted ? '#3B82F6' : '#94A3B8'}
```
Comment (anandmindfire) [inline apps/dashboard/src/components/modules/dependency-graph/components/GraphVisualization.tsx:48]: dont hardcode color directly in this

File: documentation/src/pages/MonodogLandingPage.js [hunk 3]
```diff
@@ -17,54 +17,54 @@ import {
   AlertTriangle,
   Link,
   Activity,
-} from "lucide-react";
-import "../css/monodog.css";
+} from 'lucide-react';
+import '../css/monodog.css';
 
 // --- Configuration Data ---
 const features = [
```
Comment (anandmindfire) [inline documentation/src/pages/MonodogLandingPage.js:24]: move constants seperare

**Review by anandmindfire — APPROVED** [review]
